GRANT ALL PRIVILEGES ON SCHEMA public TO config_user;
GRANT CREATE, USAGE ON SCHEMA public TO config_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO config_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO config_user;